server:
  port: 8080
  servlet:
    context-path: /diancan
spring: # 注意此处数据库设置可能需要根据情况进行修改
  datasource:
    url: jdbc:mysql://localhost:3306/oms?characterEncoding=utf-8&useSSL=false&serverTimeZone=UTC
      &useOldAliasMetadataBehavior=true&allowPublicKeyRetrieval=true
    username: root
    password: password
    hikari:
      connection-init-sql: set names utf8mb4
    tomcat:
      init-s-q-l: SET NAMES utf8mb4 #这是最重要的一步
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

