server:
  port: 8080
  servlet:
    context-path: /oms
spring:
  datasource:
    url: jdbc:mysql://159.75.136.86/oms?characterEncoding=utf-8&useSSL=false&serverTimeZone=UTC
      &useOldAliasMetadataBehavior=true&allowPublicKeyRetrieval=true
    username: root
    password: db123456
    hikari:
      connection-init-sql: set names utf8mb4
    tomcat:
      init-s-q-l: SET NAMES utf8mb4 #这是最重要的一步
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

