<head>
    <meta charset="utf-8">
    <title>点餐后台</title>
    <#--引入本地bootstarp-->
    <#assign path="${springMacroRequestContext.getContextPath()}">
    <link rel="stylesheet" href="${path}/css/bootstrap_min.css">
    <script src="${path}/js/jquery_min.js"></script>
    <script src="${path}/js/bootstrap_min.js"></script>
    <#--<link rel="stylesheet" href="/diancan/css/global.css">-->
    <link rel="stylesheet" href="${path}/css/global.css">

</head>